### ISSUE TITLE
Enter subjective teams before all quantitative scores are entered [sf#66]

### ISSUE THREAD

**Issue by jpschewe** [jpschewe/fll-sw#101]

**Comment by jpschewe** [comment]
@eengstrom is this about the subjective categories like innovative design?

**Comment by eengstrom** [comment]
> @eengstrom is this about the subjective categories like innovative design?

Yes, this is my desire to be able to _enter_ the categories _AND_ finalists in purely subjective categories (e.g innovative design) before the numeric categories are comletely tabulated/entered.

**Comment by jpschewe** [comment]
There is a non-numeric nominees link on the reporting page that allows you to do this up front now.
