### ISSUE TITLE
Scheduler - violations in 4th round not visible

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#1010]
When using the scheduler and adding a 4th performance round (practice plus rounds 1,2,3) the scheduler highlights red for warnings in the text but does not highlight the table above.  appears that the additional performance round gets no highlighting for yellow warning or red fault.

![image](https://user-images.githubusercontent.com/45802417/147514493-bce78177-734b-4b64-a346-66f212db386d.png)

**Comment by jpschewe** [comment]
@jeanniebadger  can you provide a schedule to test with?

**Comment by jpschewe** [comment]
@jeanniebadger  I believe this is working as designed. When the warning involves 2 performance runs, only the first one is highlighted.
