### ISSUE TITLE
Scheduler - error loading a second file

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#1011]
When loading a new file into the scheduler, get this error message and have to restart.  I can always run one schedule and can refresh that schedule but always get kicked out when trying to load a second schedule.

More of a nuisance than big issue
![image](https://user-images.githubusercontent.com/45802417/147514569-4898e329-b3ab-4ff6-ac38-efb69dc6e7d5.png)
[fll-sw_2021-12-27_17-58-59.1.log](https://github.com/jpschewe/fll-sw/files/7782072/fll-sw_2021-12-27_17-58-59.1.log)

**Comment by jpschewe** [comment]
@jeanniebadger  please try a build from https://jenkins.mtu.net/job/FLL-SW/job/issues%252F1011%252Fschedule-load/ and see if this is still an issue for you.

**Comment by jeanniebadger** [comment]
![image](https://user-images.githubusercontent.com/45802417/147593382-d028030e-ea0a-4947-8d24-129189463185.png)
Yes, I received the same error message

**Comment by jpschewe** [comment]
@jeanniebadger  please attach the schedules that you are using and the exact steps you follow to cause this error. I had the error before those changes and it went away with the newer build.

**Comment by jpschewe** [comment]
Working with Jeannie through direct email.

**Comment by jpschewe** [comment]
@jeanniebadger  have you been able to reproduce this with the latest build at https://jenkins.mtu.net/job/FLL-SW/job/issues%252F1011%252Fschedule-load/lastSuccessfulBuild/artifact/

**Comment by jeanniebadger** [comment]
I will do some more testing of this and get back to you

**Comment by jpschewe** [comment]
Jeannie sent me data files and a video and I was able to reproduce this.
https://drive.google.com/file/d/1MYO2F48HzN7qasJWN_-3pAJH3F1Ycn8q/view?usp=drive_web
[Prior_Lake_Sat_11-20-21_Regional_Schedule.xlsx](https://github.com/jpschewe/fll-sw/files/9050466/Prior_Lake_Sat_11-20-21_Regional_Schedule.xlsx)
[Prior_Lake_Sat_11-20-21_Regional_Schedulev2.xlsx](https://github.com/jpschewe/fll-sw/files/9050467/Prior_Lake_Sat_11-20-21_Regional_Schedulev2.xlsx)
