### ISSUE TITLE
error loading xml 8 into version 16.5

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#1044]
![image](https://user-images.githubusercontent.com/45802417/190021168-263cac13-eee8-4e84-9514-13b6373b01ed.png)

**Comment by jeanniebadger** [comment]
When trying to load into Editor.

Loaded without error with version fll-sw-windows-16.5.1-beta.174+g22cfd5b

**Comment by jpschewe** [comment]
@jeanniebadger  you need to use 16.5.1-beta.174 or later as that field was added after this.
