### ISSUE TITLE
Detailed Team Schedule

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#1181]
The Scheduler generates a Detailed Team Schedule - similar to what is on the pit sign

It would be nice to have this in the Admin section of the software so if a Pit sign is lost or Head Judge needs to quick look up the team schedule and not have to rely on HTK crazy looking schedule 

Note - this is from the Non-Advancing so it has a 5th Performance run

[Capitol Hill Non-Advancing 3-23-24-team-schedules.pdf](https://github.com/jpschewe/fll-sw/files/14563001/Capitol.Hill.Non-Advancing.3-23-24-team-schedules.pdf)

Tasks:

- [x] store schedule parameters
- [x] output all schedules
- [x] allow user to specify team to output
- [x] Add selecting the team to the public page

**Comment by jpschewe** [comment]
I'll need to add a link to something that calls "ScheduleWriter.outputTeamSchedules(this, params, pdfFos)"

**Comment by jpschewe** [comment]
The challenge here is that the schedule parameters are required to call this method and those are not currently stored in the database.
