### ISSUE TITLE
Export of Awards and team number and name

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#1182]
Report request for Export of Award, Team name and Team number for each tournament
This will be helpful to assist with Shipping of awards

Currently have to re-type that info into a spreadsheet for shipping  - 

Priority Medium

**Comment by jpschewe** [comment]
Sample table based on spreadsheet from Jeannie.

Award | Team Number | Team Name
-- | -- | --
Champion | 3272 | JP2 Fireworks 2.0
Champion | 37796 | Chicken Coup
Champion | 4261 | Better Blake Bots
Core Values | 50145 | RoboRaptors
Core Values | 3858 | THEY WHO MUST NOT BE NAMED
Project | 1234 | Jeannie Team
Project | 55555 | Another team

**Comment by jpschewe** [comment]
@jeanniebadger  do you need the place for the awards? Or is it sufficient to have which teams received which awards and order doesn't matter?

**Comment by jpschewe** [comment]
From Jeannie: Would just need award.  Rank only matters at state and we don't ship those
