### ISSUE TITLE
auto-generate/"mail-merge"-version of awards script [sf#176]

### ISSUE THREAD

**Issue by jpschewe** [jpschewe/fll-sw#211]
Would be nice to auto-generate the ENTIRE awards script.  Will require that some amount of "template" is provided, and some way to specify the query to collect the winner(s).

Would also be nice if the report could include not just the first place, but the top "n" places for each category, with scores, so the head judge could "select" (circle) the actual winner, in case of ties...

  - [x] Make sure that Championship is able to be awarded at all tournaments. This should be handled as an implicit numeric category based on the overall score and it is per award group.
  - [x] interface for editing the season version of the script
  - [x] interface for editing the level version of the script - allows override of season
  - [x] interface for editing the tournament version of the script - allows override of level
  - items to edit
    - [x] front end text - default in code, generally set per season
    - [x] list of sponsors, order matters - generally set per level
    - [x] text that is below the sponsors - default in code
    - [x] text before awards
      - [x] school name
      - [x] tournament director names
    - [x] allow order of awards to be specified, including per award group
      - using the order of award groups from the advancing team list
    - [x] allow one to enter presenter per award
    - [x] Per-award text, make sure to include Championship
    - [x] final text notes
      - [x] number of trained officials
      - [x] number of advancing teams
    - [x] allow specification of order of award groups for advancement, including wildcard. *Can probably take this from the awards report*
  - [x] page breaks after each award. Keep rows of the tables together
  - [x] skip awards that don't have any teams listed
  - [x] If there is a finalist schedule and the category is listed, then display the finalists in the awards script
  - [x] display 2nd place and 1st place for awards where possible
  - [x] database storage for text
  - [x] database storage for sponsor names
  - [x] database storage for award order
  - [x] database storage for award presenters
  - [x] database storage for per-award text
  - [x] Allow specification of number of performance winners
  - [x] Update import of database for the new tables
  - [x] Include support for head to head if the tournament is using it
  - [ ] when to display places

**Comment by jeanniebadger** [comment]
The scripts for Regional and Sectional are similar.  State is more involved.
[2019 FLL City Shaper Regional Awards Script.docx](https://github.com/jpschewe/fll-sw/files/3995994/2019.FLL.City.Shaper.Regional.Awards.Script.docx)
[3 Divisions - 2019 FLL City Shaper Regional Awards Script.docx](https://github.com/jpschewe/fll-sw/files/3995995/3.Divisions.-.2019.FLL.City.Shaper.Regional.Awards.Script.docx)
[2019 FLL City Shaper Regional Awards Script. One division.docx](https://github.com/jpschewe/fll-sw/files/3995997/2019.FLL.City.Shaper.Regional.Awards.Script.One.division.docx)
[State AwardScript 2019-TeamAwardsP2.docx](https://github.com/jpschewe/fll-sw/files/3996011/State.AwardScript.2019-TeamAwardsP2.docx)

**Comment by jpschewe** [comment]
Script for a tournament in the 2020 season.
[3_Divisions_-_2020_FLLC_RePlay_Regional_Awards_Script.docx](https://github.com/jpschewe/fll-sw/files/5929406/3_Divisions_-_2020_FLLC_RePlay_Regional_Awards_Script.docx)

**Comment by jpschewe** [comment]
Reviewing the documents from 2019 and 2020 I see the following items for entry:
- get date, tournament name and number of award groups from the database
- need list of sponsors input
- allow sponsors boilerplate to be specified
- host school and tournament director
- award group to table name for where to pickup awards, or note that they will be emailed out
- Note about advancement (sectionals or state or world)
- allow the award order to be specified
- Need an interface for allowing the head judge to pick the winner from the top N teams in each award. This can probably come from the award winners report
- end of award presentation text

The boiler plate text needs to be entered per tournament, but is the same for many tournaments. Maybe see if there is a way to enter this once?

Need a way to allow markup of bold text.

**Comment by jpschewe** [comment]
@jeanniebadger  is going to take a first pass at a generic document. Make sure to look at my previous comment where I started an outline.

**Comment by jeanniebadger** [comment]
Thinking out loud:
We know the following before any events happen and before any schedules are generated: Tournament Dates, Tournament Name, Tournament #, Locations, Tournament Directors, and Awards Groups (generally - the # of Judging groups has sometimes been increased or decreased by one group but that calculation happens once registration is complete), Advancement to level (regional to sectional to state or regional to state), Number of teams advancing from each judging group (may not know exact number of teams advancing as that can be changed if # of Judging groups change).  We also know the Sponsor names (though local tournaments may want to add that to their script - but i don't know that we need to accommodate for that).  

All the above info comes after the XML has been created and tested but prior to any scheduling of teams.

Could these pieces of data be entered via an "Admin tab" or "HTK Tournament" tab and create a "Tournament table" to pull for the Script.  Then the actual database with team and award info is pulled from Judges entries day of the tournament.

Could Script "blah blah blah" be entered under the same Admin or HTK tab?

Truth be told, the Script "blah blah blah" is often (always) written out the week of the first tournament!

When each schedule is created it would need to be correctly aligned to "Tournament Table".

So I am picturing data coming from 4 places (?) XML, Tournament Table, Judges Input, Database (scores, team #, team names)

**Comment by jpschewe** [comment]
When thinking about information, don't necessarily think about which tab it lives on. Think about what it should be associated with. I think our categories for data are:
- challenge XML - this is the challenge information, this may not be specific to Minnesota
- season - information that is common to all tournaments in Minnesota for the current season
- level - information that is common for each level of tournament play (regional, sectional, state).
- tournament - information that is for a specific tournament. eg. name, location, number of judging groups. 
- scores - technically this is associated with the tournament, but probably easier to think about it separately. This would include the winners and the text about the winners.

Note that I already have information associated with the tournament and the season. I have not specifically setup data associated with the level, but that can be added.

**Comment by jeanniebadger** [comment]
ok, this is helpful for putting together the script

**Comment by jpschewe** [comment]
I have a version of the script that Jeannie and I have agreed to that should work for all tournaments. The next step is to design get into details of how the information is input.

**Comment by jpschewe** [comment]
Database storage for text needs:
- section name
- identifier for layer (season => null, tournament level => level_id, tournament => tournament_id)
- layer rank - give each layer a numeric value to make it easy to select the appropriate text for the final script. 

Use a Java enum for award script layer (name, rank). The database stores the rank to make select easy.
