### ISSUE TITLE
Make subjective score summary easier to read

### ISSUE THREAD

**Issue by jpschewe** [jpschewe/fll-sw#357]
The big table can be confusing to read. Perhaps making the row headers bold will help. There should be 2 columns of headers. Maybe use "2 scores" instead of 2 or "2 judges"?

**Comment by eengstrom** [comment]
I had the same thought and have a partial implementation to make it better.  Will try to finish before state.

**Comment by jpschewe** [comment]
Note that this is in the subjective scoring Java application. Not the
subjective web application.

On Mon, Jan 12, 2015 at 9:35 AM, Eric Engstrom <notifications@github.com>
wrote:

> I had the same thought and have a partial implementation to make it
> better. Will try to finish before state.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jpschewe/fll-sw/issues/357#issuecomment-69587683>.
>



-- 
http://mtu.net/~jpschewe

**Comment by eengstrom** [comment]
Oh, I have some of the same issues with the web app version.

**Comment by jpschewe** [comment]
Subjective java application was removed in #855 this is OBE.
