### ISSUE TITLE
PDF subjective score sheets

### ISSUE THREAD

**Issue by jpschewe** [jpschewe/fll-sw#394]
PDF versions of the subjective score sheets with team and schedule information.

Note that this needs to handle a missing schedule. 

It should be generic in that can handle any challenge description and not rely upon special knowledge in the code of what we expect for category names.

We'll need to have some way of prompted the user for which schedule columns line up with which categories, otherwise one can't figure out the schedule. 

It would also be nice to be able to generate these sheets from the web too. Once it's working through the ScheduilerUI, this should be pretty easy like the other schedule PDFs.

**Comment by jpschewe** [comment]
Make sure that we have 1 file per category so that when printing we can print each category on different colored paper.

Also do what we can to get as much of the team name visible, enlarge the box, shrink the font size if the team name is long, stuff like that.

**Comment by schleus** [comment]
Jon,
 I'll be actively working on this starting Monday (when I'm completely back from Yellowstone). Any suggested max length on the name? I've been using a Rochester sheet with "masters of disaster 2.0" as a target length. 

Each category also currently prints on its own PDF per file.



Mark T Schleusner

**Comment by jpschewe** [comment]
Make the space as big as possible. Then see how many characters fit and chop it at that. What I have done with other places is replace it with "..." at the end to show that the name has been chopped off. There is a getTrimmedName() method on Team that limits the length to 24 characters. This is used in a number of places.
