### ISSUE TITLE
Bigger font on the scoreboard pages

### ISSUE THREAD

**Issue by eengstrom** [jpschewe/fll-sw#425]

**Comment by eengstrom** [comment]
As an observer, it seemed like there was lots of white space that could be more effectively used

**Comment by jpschewe** [comment]
At a minimum we should use the same fonts for the playoff brackets as are used on the score board.

If you  have any suggestions on a better layout, I'm open to them.

**Comment by jpschewe** [comment]
- [ ] The font for the right side of the scoreboard looks pretty good. Make the left side be the same.
  - [ ] Make the playoff bracket font larger
  - [ ] make font size larger on finalist schedule that is on the big screen

**Comment by jpschewe** [comment]
Define a CSS class for scoreboard text and use it universally to set the front family and size

**Comment by jpschewe** [comment]
See http://www.quirksmode.org/css/quirksmode.html and make sure that the doctype is set. If it's not set, then many of our CSS parameters are ignored.
