### ISSUE TITLE
Printed head-to-head scoresheets have wrong bracket number

### ISSUE THREAD

**Issue by churchid** [jpschewe/fll-sw#461]
On 1/9/16 in the first 3-division subsection tourney, Vince reported that bracket numbers on head-to-head scoresheets were incorrect after limiting table colors.

On 1/10, in the next 3-division subsection tourney, I initialized Lakes, then on the scoresheet generation page limited table assignment to the blue tables. The bracket numbers in the generated scoresheets, in order of occurrence for the 16 teams in round 1, were: 3, 2, 6, 6, 2, 7, 1, 5, 5, 1, 5, 1, 7, 2, 2, 1.

Then, I initialized Prairie, and limited table colors to yellow. For this division, the color limiting didn't work, and it assigned tables at both yellow and red tables. I selected all yellow tables, then generated the scoresheets. The brackets on the printed scoresheets for the 12 teams (there was a bye for the first and second-place teams in this division) were 5, 8, 7, 2, 1, 7, 1, 3, 8, 5, 4, 8. Color assignment in subsequent rounds worked correctly.

Finally, I initialized Woods division, and limited the table colors to red tables. Everything for this division worked correctly, including both the color limitations and the bracket numbers on the scoresheets.

**Comment by jpschewe** [comment]
I was able to reproduce this by the following:
  1. Load the database from 1/10
  1. uninitialize each playoff
  1. DELETE FROM table_division WHERE tournament = 2 // use the tournament id for the 1/10 tournament from the tournaments table
  1. Initialize lakes
  1. limit to blue tables
  1. press print

**Comment by jpschewe** [comment]
Just loading the database and reprinting the score sheets does not show the problem.
