### ISSUE TITLE
Look into integration with FIRST software

### ISSUE THREAD

**Issue by jpschewe** [jpschewe/fll-sw#473]
FIRST has decided to go with the software from the Netherlands. The protocols for communicating with it can be found at https://github.com/FirstLegoLeague/mq-protocols. We should look closely at what they after doing and see if we can use a common message bus, particularly for the subjective scoring.

**Comment by jpschewe** [comment]
On June 6, 2016 I was in a call with the group leading this message bus implementation. We should look into their message bus and websockets and see where it makes sense to modify our architecture so that our modules can be used with their system and we can potentially use their modules. We need to keep in mind how easy it is to install. I've finally gotten FLL-SW to the point where I believe it's a really easy install (zip file + Java) and I don't want to go backward at all.

**Comment by eengstrom** [comment]
I did a very quick glance at the FLL MQ/MessageBus stuff and I'm not sure it's going to scale, and I'm very concerned about lost messages (does the protocol define `ack` to ensure that all scores are registered. 

That said, we have a lot of technical debt that we could reduce and perhaps eliminate.  You may feel strongly that we have a good working software, and while that's true, perhaps we need to consider the fact that we've gotten to 20 years and haven't change the underlying architecture much as an indication that we are in need of a deep look into how we can move forward.  Also, I think if we can contribute modules to the core software, we might be able to get them to move (a bit) to our "quantified subjective" judging system.

Just thoughts as I see them.

**Comment by jpschewe** [comment]
@eengstrom I too am concerned about the scalability and lost messages. Personally I prefer the central server model, especially since it's worked well for us in the past.

Issue #599 is for publishing our subjective judging scores to their message bus. I think that if we implemented that, they might accept it.

Implementing #577 should make their display look better with our scores, the current list module really does look bad with all of the information we send.

I would like to leverage other software where possible and keep from breaking what we have for the Minnesota tournaments. At this point I feel like I'm just keeping up with the things that I want/need to add to FLL-SW without doing a lot of integration work.

**Comment by jpschewe** [comment]
This software appears to have gone away.
