### ISSUE TITLE
Judges' final worksheet [sf#17]

### ISSUE THREAD

**Issue by jpschewe** [jpschewe/fll-sw#52]
IMO, it would be nice to have a final worksheet for each judge to fill out during both regionals (w/ no finalist re-judging) and states (with finalists). In this report would be:
* 1st place for each P/D/I
* 2nd place
* Paragraph for I
* Name / Div / Team #
* Judge Name / Phone #

The judges would fill this out and return to the head judge along with their score matrix.

If I recall what I was thinking, this is just paperwork, not software -
need to coordinate with Norm on this one.

**Comment by jpschewe** [comment]
@eengstrom is this still something you want/need?

**Comment by eengstrom** [comment]
I think this is just paperwork that has a form in Norm's package of stuff, so let's focus on other things.
