### ISSUE TITLE
Option to sort teams by number of runs

### ISSUE THREAD

**Issue by codetheweb** [jpschewe/fll-sw#529]
Add an option to sort the teams on the score entry page by the number of runs (in ascending order).  Then the teams that just ran would generally be displayed first.

**Comment by jpschewe** [comment]
Would you suggest always sorting by number of runs, then team number? Or make it an option?
The downside of airways sitting this way is possible issues when looking for a team to correct, but that doesn't come up much.

Maybe add a box to type team numbers into?

**Comment by codetheweb** [comment]
I meant that when the option was turned on, the list of teams would be sorted by number of runs and then the team number.  Something to find a team by number would also be helpful, maybe something like this:
![team sorting](https://cloud.githubusercontent.com/assets/7410405/21082540/1fe43a30-bfa3-11e6-97f3-8d31a4880866.png)

**Comment by jpschewe** [comment]
Right, I was wondering if there should be an option or just always sorted
this way.

**Comment by jpschewe** [comment]
During the seeding rounds sorting by fewest number of runs will be quite useful. During head to head this sort will probably not be helpful as the final teams will have more runs than anyone else. So we'll want to be able to recognize that and change the sort. Ideally the box would only show teams that can do another run. So during the seeding runs this would only show teams with fewer than 3 runs and during head to head it would only show teams still in the head to head. There will need to be a way to see all teams and runs for editing purposes.

**Comment by jpschewe** [comment]
With the changes to sort by schedule and display the next run number, I would say this is resolved.
