### ISSUE TITLE
QR code generated on server with address of server for use on tablets (Feature idea)

### ISSUE THREAD

**Issue by eengstrom** [jpschewe/fll-sw#647]
Ignoring for the moment issue #277, another quick way to help users find the server, espeically for BYOD for the subjective app, might be to generate a QR code that we print (paper or sticker) and put in the judge packets.  The QR code would encode the server address (and port).  

IFF we ever open up the server to guest usage, we could also post that QR code around the tournament, or display on the big screen.

**Comment by jpschewe** [comment]
@eengstrom I like that idea. It is simple and should not require much to be loaded on the devices. I'd like to see a manual test of this and determine what needs to be done in the tablet for it to work.

**Comment by jpschewe** [comment]
Here are instructions for IOS

**Comment by jpschewe** [comment]
Looks like Android needs an app

**Comment by jpschewe** [comment]
Options for Java https://stackoverflow.com/questions/7195007/what-is-the-best-java-qr-code-generator-library

**Comment by jpschewe** [comment]
We are moving toward using servers on the internet all of the time now, so this no longer applies.
