### ISSUE TITLE
Upgrade to JDK 11+

### ISSUE THREAD

**Issue by jpschewe** [jpschewe/fll-sw#648]
JDK 10 is out. Things to consider:

- [x] When does JDK 8 hit end of life? -> 4/16/2019
- [x] What features are available in JDK 9 and 10 and 11 that we may want to use?
   - new stream functions
- [x] How hard is it for the users to have JDK 11?
  - need to bundle the JDK - #399
- [x] Is our launcher compatible with JDK 11?
  - yes, if we bundle the JDK, #399
- [x] need to figure out spotbugs with Java 11
  - getting errors about a null check for a previously dereferenced value. This is happening with the code generated for try with resources
    - https://github.com/spotbugs/spotbugs/issues/756
  - errors about redundant null check
  - errors about private methods not called that are called from inner classes
- [x] figure out how to launch HTML files properly, seems to be an issue with Java 8 as well, see #748
- [x] resolve dnsjava issue about reflective access
  - https://github.com/dnsjava/dnsjava/issues/8
  - this should be fixed in the next version after 2.1.9

**Comment by eengstrom** [comment]
Just a thought based upon recent news:  Do we use serialization anywhere?  If so:

https://developers.slashdot.org/story/18/05/26/0520227/oracle-calls-java-serialization-a-horrible-mistake-plans-to-dump-it

**Comment by jpschewe** [comment]
I don't believe we use serialization because we want to be compatible with other tools that may not be Java.

**Comment by jpschewe** [comment]
OpenJDK supports zip and tar downloads of the JVM for platforms. This makes packaging fairly easy. I suspect this is the direction to go for an easier install.

I also see that JavaFX is include in OpenJDK 11, which may be a direction to go for the stand-alone Java applications.

**Comment by jpschewe** [comment]
Launch4j may have an issue with this https://sourceforge.net/p/launch4j/bugs/186/

**Comment by jpschewe** [comment]
log4j uses multi-release jar files. i handled this in another project with this commit https://github.com/jpschewe/google-calendar-agenda-cleanup/commit/907c43e0a35ed40cd5d2e51117224025177b22a3.
In this case the jar file was built with opendjk 8, but run on openjdk 11.

**Comment by jpschewe** [comment]
I checked the other day and openjdk 12 is the current download, there is no download for openjdk 11. Ubuntu 18.04 is currently shipping openjdk 11 and no option for 12 yet.

**Comment by jpschewe** [comment]
SpotBugs doesn't support java 11 yet. I tried running it with Java 11 and got all kinds of warnings about extra null checks that aren't in the code.

**Comment by jpschewe** [comment]
I build using openjdk 11 under Linux and then tried running under openjdk 12 under Windows 10. The launch4j executable complained that java 11.0.0 was required. However I was able to launch it from the command line. I got an error that fll-sw.html couldn't be found even though the correct path was specified.

Got some warnings about dnsjava
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.xbill.DNS.ResolverConfig (file:/C:/Users/User/Desktop/fll-sw-13.5.1-beta.190+g4484552/fll-sw-13.5.1-beta.190+g4484552/lib/dnsjava-2.1.8.jar) to method sun.net.dns.ResolverConfiguration.open()
WARNING: Please consider reporting this to the maintainers of org.xbill.DNS.ResolverConfig
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
This is being tracked at https://github.com/dnsjava/dnsjava/issues/8

**Comment by jpschewe** [comment]
Some clues on getting the Windows executable to work with openjdk 12
* https://sourceforge.net/p/launch4j/feature-requests/127/
* https://sourceforge.net/p/launch4j/bugs/197/

The base problem is that there is no installer for openjdk, therefore the registry entries don't get set and the fll-sw.exe (launch4j) thinks there is no Java VM installed, even if it's on the path.
It sounds like bundling the JVM with the application is the best solution. Then it's no concern.

**Comment by jpschewe** [comment]
The method `Predicate::not` will be quite useful when moving to Java 11. See the enumerate functions in `TournamentScheduleInfo`.

I think that to move to Java 11 we should have the JDK bundled with the at least the Windows installer, #399, so that we don't have issues with users needing to figure out how to install OpenJDK.

**Comment by jpschewe** [comment]
Consider using PMD instead of SpotBugs, it claims to support Java 13.

**Comment by jpschewe** [comment]
I have upgraded to spotbugs 2.0.1 with tool version 4.0.0-beta4, however that still shows errors around the try with resources statements.
