### ISSUE TITLE
Score entry page mission number display

### ISSUE THREAD

**Issue by rudolph4404** [jpschewe/fll-sw#675]
On the score entry page, repeat the mission number over the mission values. This would aid the visual verification scanning.

**Comment by jpschewe** [comment]
This is something that is not part of the software, but rather party of the challenge description. It's up to the person wiring the challenge description to handle this.

**Comment by jpschewe** [comment]
I may have closed this too soon.

This is related to how grouped goals are displayed. The category name could be repeated. We haven't done this because then the page doesn't match the score sheet. We don't want to repeat this information on the score sheet because then it's too long.

**Comment by jpschewe** [comment]
@rudolph4404 just repeating the grouping text on each goal in the web page entry be sufficient? Or would you want this on the score sheet as well?

**Comment by rudolph4404** [comment]
Just on the web page should be sufficient. -ChuckOn Dec 2, 2018 8:04 AM, Jon Schewe <notifications@github.com> wrote:@rudolph4404 just repeating the grouping text on each goal in the web page entry be sufficient? Or would you want this on the score sheet as well?
