### ISSUE TITLE
Add the ability to post messages to the big screen display

### ISSUE THREAD

**Issue by rudolph4404** [jpschewe/fll-sw#683]
It would be nice to be able to post arbitrary messages via the big screen display.
A right to left scrolling message at either the top or bottom of the display for announcements.
For example:
-  car lights on
- need to move car because you're blocking someone in and about to get towed
- found cell phone

I think we used to have something like this - not sure where it went...

-Chuck

**Comment by jpschewe** [comment]
It's still there. You change the text on the admin page under "Scoring display text". The first item under "Tournament Day".
