### ISSUE TITLE
Tech Idea: find non-discoverable bluetooth devices

### ISSUE THREAD

**Issue by eengstrom** [jpschewe/fll-sw#731]
In order to remove some restrictions on electronics in the performance area, could we use some interesting tech to find (locate) the devices.  I was perusing the webs and ran across at least one thing: [ubertooth](https://github.com/greatscottgadgets/ubertooth) (and [ubertooth one](https://greatscottgadgets.com/ubertoothone/)) or some iDevice/Android scanning software.  Best if it could find by manufacturer id and spit out those that belong to LEGO.

**Comment by jpschewe** [comment]
@eengstrom I'm not sure what restrictions you are talking about. I'm not currently aware of any restrictions on electronics in the performance area, other than remotes for the robots.

**Comment by jpschewe** [comment]
We are moving toward using servers on the internet all of the time now, so this no longer applies.
