### ISSUE TITLE
"No Number" subjective judging app

### ISSUE THREAD

**Issue by eengstrom** [jpschewe/fll-sw#732]
As I described previously, it would be an interesting experiment to take the numbers out of the subjective judging app.  That is, instead of entering numbers, have the app have sliders that allow the judges to simply move the index left or right (or perhaps up/down) for each subcategory, matching the rubric:  Needs Improvement to Exemplary (or whatever titles).  

Behind it, the numbers still exist, but the judge never sees them.  

Ideally, said update would eliminate the 11x17 sheets entirely, but we'd obviously like some form of backup.

**Comment by jpschewe** [comment]
You should talk to @jeanniebadger about this. She is reworking the score sheets and the bit sheets for this season.

**Comment by jpschewe** [comment]
@eengstrom take a look at the latest release and see what you think. The only number visible is the score at the top. There are no numbers per goal.
