### ISSUE TITLE
Webserver not able to find web root

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#743]
Downloaded from Build #6
![image](https://user-images.githubusercontent.com/45802417/62077444-b60bf000-b20f-11e9-8464-a26da9499d21.png)
Extracted file to new folder and ran .exe from extracted folder
[fll-sw_2019-07-29_14-37-22.1.txt](https://github.com/jpschewe/fll-sw/files/3444094/fll-sw_2019-07-29_14-37-22.1.txt)

**Comment by jpschewe** [comment]
This is build 6 from the branch issue/432/web-app-rework.

Relates to issue #432.

**Comment by jpschewe** [comment]
I think the new version of launch4j introduced recently somehow sets the code since to the executable instead of the location of the classes.
