### ISSUE TITLE
Subjective Scoring Interface request - make slider handle more obvious

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#745]
In showing the tablet app to both Norm and Vicki, they had trouble initially finding the box to move the slider for scoring.  

Can the slider grab box be black or bold outlined to make it more obvious?

**Comment by jpschewe** [comment]
@jeanniebadger I have made the slider handle black. I believe this will address the issue. See build 9 or later of branch issue/432/web-app-rework.

**Comment by jpschewe** [comment]
@jeanniebadger  actually, watch for master build 92 or later.
