### ISSUE TITLE
Subject Score app on tablet - lock rubric range names in header

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#746]
Would like the Team name, number, score and Scoring Categories to remain static while scrolling through the scoring app.  Sometimes it is and sometimes it is not.  May need testing to figure out when it stays put.

Would like it to always read similar to this across the top of the page when entering scores

![image](https://user-images.githubusercontent.com/45802417/62166170-aced5280-b2e5-11e9-9e0d-f29974b9a271.png)

**Comment by jpschewe** [comment]
When you say scoring categories, are you referring to beginning, exemplary, etc?

**Comment by jeanniebadger** [comment]
Yes The Beginning, Exemplary etc

**Comment by jpschewe** [comment]
@jeanniebadger the challenge here is that I need to have 2 tables to do this. One for the header and one for the content. This means that I can't guarantee that the widths of the columns are the same and the headers won't necessarily line up with the rubrics. One option would be to put the headers above each goal name?

**Comment by jeanniebadger** [comment]
putting headers over each goal will work but will make the screen longer.

**Comment by jpschewe** [comment]
Turns out that with the changes to the table layout I'm able to do this without nearly as much trouble as I thought it would be. Watch for a new master build once this ticket closes.
