### ISSUE TITLE
Subjective Scoring app - can copy paste from screen

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#747]
When clicking around on the subjective app on tablet, I can highlight and copy text from the Score and Category descriptions.  

Doesn't seem to be an issue as it doesn't remove text or allow user to overwrite text, but it may cause confusion to people if they think they have done something wrong.

Is there a way to prohibit the selection of text?

Priority:  Lowish

**Comment by jpschewe** [comment]
Its like any other web page or application. You can highlight text. I'll see what I can do, but it is working against how standard applications work.

**Comment by jeanniebadger** [comment]
Not a high Priority - just a comment
