### ISSUE TITLE
App Launch Message - failed to open fll-sw.html

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#748]
I did get a message that said 

![image](https://user-images.githubusercontent.com/45802417/62168169-8c73c700-b2ea-11e9-9637-012996344777.png)

But if I remember correctly, you said that would happen.  I just went back to the folder and double clicked the Chrome file and it opened fine.

![image](https://user-images.githubusercontent.com/45802417/62168191-94cc0200-b2ea-11e9-82fb-e0f888049681.png)

**Comment by jpschewe** [comment]
@jeanniebadger  is this with the Java 8 (1.8) that you were using to test before or is this with a newer Java install?

**Comment by jeanniebadger** [comment]
it was with Java i

![image](https://user-images.githubusercontent.com/45802417/62378714-0edad180-b50b-11e9-94f4-ccf5b7aec326.png)

**Comment by jpschewe** [comment]
Thanks. I believe this is fixed now.
