### ISSUE TITLE
Category labels across top of judging app - mulitplying

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#751]
With each successive team score entry, the Category titles of Beginning, Developing, Accomplished, Exemplary multiples.  See example.  Same thing happens when using a laptop to enter judging scores.  Scrolling works well - but will be frustrating for the last teams entered.

Image from tablet:

![image](https://user-images.githubusercontent.com/45802417/62901261-ec726080-bd21-11e9-8e1a-e2d45d635cea.png)
  
Image from laptop:

![image](https://user-images.githubusercontent.com/45802417/62901209-d19fec00-bd21-11e9-87e5-6364621dd5b0.png)

**Comment by jpschewe** [comment]
I need to make sure to clear that field when loading a new score.
