### ISSUE TITLE
printing rubrics - wrong number of columns message

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#752]
I receive the following error when trying to print rubric from Main Index and from Scheduler
![image](https://user-images.githubusercontent.com/45802417/62903800-88ec3100-bd29-11e9-8985-83c473ce7d0a.png)
[bug_2019-08-12_17-51904118447269202108.zip](https://github.com/jpschewe/fll-sw/files/3494602/bug_2019-08-12_17-51904118447269202108.zip)

![image](https://user-images.githubusercontent.com/45802417/62903705-44f92c00-bd29-11e9-910f-3dd4ef24b575.png)

![image](https://user-images.githubusercontent.com/45802417/62903738-58a49280-bd29-11e9-8594-c004c57de422.png)

Bug report is attached

**Comment by jpschewe** [comment]
Found the initial problem and got rid of the exception. However now the table columns are all wrong. I suspect there are more constants in the code that need to change.
