### ISSUE TITLE
Directions/instructions for Rubrics has changed

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#753]
The instructions at the top of each rubric have changed and include better directions than in past years.  I would like to update to say the same as the FIRST rubrics but I don't see that in the xml file.  The text is different for each Rubric, so if that is a problem we can figure out what we like to keep and what may become part of verbal instructions to judges

**Comment by jpschewe** [comment]
The text is currently the same on all sheets, correct? Then making it different for each category is going to take some work. I will look into making this part of the XML file. In the meantime, think about how different they are and if we need them different.

**Comment by jpschewe** [comment]
I thought about this more last night and it should not be very difficult to support specifying these instructions in the XML file. To be clear, the directions are per category, not per goal or per grouping of goals. Correct?

**Comment by jeanniebadger** [comment]
I can make them all the same for this season but will need to adjust a little bit.  I will figure out the text and send it to you so we can improve the instructions for this season.

Would like to have them the same as FIRST rubrics, but not a priority this season

**Comment by jpschewe** [comment]
Am I correct that this text is per category, not per goal?

**Comment by jeanniebadger** [comment]
The text is at the top of each Rubric - ie.  this is what  Robot Design says
"For each Robot Design Criteria, clearly mark the box that best describes the ability of the team to demonstrate or provide evidence (such as analysis or test data) that their robot and processes meet that level of acheivement.  If the team does NOT describe a particular criteria at all, then put an "X" in the first box for Not Demonstrated (ND).  ETC (there is more text there)

Core Values says less
"For each skill area, clearly mark the box that best describes the team's accomplishments.  ...ETC (there is more text)

So it is in the instructions at the top of each Rubric and is different for each Rubric
"

**Comment by jpschewe** [comment]
That's what I thought. I'll may be able to add this over the next week.

**Comment by jpschewe** [comment]
I've added the ability to specify the score sheet instructions in the XML file. If nothing is in the XML file, the instructions that we have used in the past are printed in the score sheets. 

I've updated the editor to allow editing this field.

I've updated the 2019 challenge description per the rubrics specified at http://www.firstlegoleague.org/challenge
