### ISSUE TITLE
Non-graphic judge score input for outstate

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#754]
Wondering if a non-graphic entry system for out state would be helpful.  I know Joe Pike commented on how time consuming it was for him to enter scores from the big sheet and having to pull down.  When I was up in Hermantown last year, the Head Judge took pics of the big sheets and turned them in throughout the day to make score entry less tedious.

Thoughts?

**Comment by jpschewe** [comment]
There is the subjective application that you can run from the launcher. This is essentially a spreadsheet. This is really the best way to do bulk entry of scores.

Is there a reason that this won't work?

**Comment by jeanniebadger** [comment]
In thinking about this, we are taking away numbers on purpose.  I worked through and entered based on where they circled on the rubric and it should be fine.
