### ISSUE TITLE
Add "Dots" to Scoring App to delineate low/med/high

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#755]
I am going to change my "Judges Worksheet" to have "Open Dots" under each Judging Goal- 3 in each Category.  THese dots will replace the number I currently have.  Would this be possible to overlay the dots on the app slider so that people get the understanding that there are 3 locations/selections within each category - ie.  Low Beginning, Medium Beginning, High Beginning.

I have attached a pdf with just the first goal changed to give you an idea of what I'm looking for.
[Research Judge Note taking-score sheet with dots.pdf](https://github.com/jpschewe/fll-sw/files/3536459/Research.Judge.Note.taking-score.sheet.with.dots.pdf)

**Comment by jpschewe** [comment]
I will need to do some investigating to see if I can add tick marks to the slider. I think I can.

**Comment by jpschewe** [comment]
@jeanniebadger please try the build athttps://mtu.net/jenkins/job/FLL-SW/job/issue%252F755%252Fslider-ticks/4/

This has fits for the values. Is this good or would you like done changes to it?

**Comment by jeanniebadger** [comment]
Looks good.  I will show it to Barb tomorrow and see if she has thoughts.  My only thought is maybe the circles could be a little smaller but that is minor.  I will let you know what Barb has to say.

**Comment by jeanniebadger** [comment]
Consensus is keep the dots the size they are!!  Barb, Norm and Vicki all had positive to say about the dots!  

Let's make this a part of the app

**Comment by jpschewe** [comment]
OK, it's merged in. Watch for build 112 of master or later at https://mtu.net/jenkins/job/FLL-SW/job/master/
