### ISSUE TITLE
Error message with uploading xml into software

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#756]
I have updated the Rubrics.  Get the following message when I upload the xml into your software
[bug_2019-08-23_18-005447529541810702034.zip](https://github.com/jpschewe/fll-sw/files/3536488/bug_2019-08-23_18-005447529541810702034.zip)

![image](https://user-images.githubusercontent.com/45802417/63627940-9201bb80-c5cf-11e9-9123-04290d86d7d4.png)

I have also attached the bug report.  I did incremental saves so I can go back a ways to find an xml that doesn't create the error but it is ALOT of changes before I discovered the error.

If it is easy (?) to track the error, let me know.  Otherwise I can go back and re-update the rubrics.

**Comment by jpschewe** [comment]
Are you editing the XML by hand or using the application?

If by hand, then goto line 582 of the file and that will be where the error is. You will want to be using some kind of text editor that shows line numbers. I'm pretty sure that Atom will (https://atom.io/). There's also Notepad++ (https://notepad-plus-plus.org/).

Alternatively send me the XML and I can take a look.

**Comment by jeanniebadger** [comment]
I downloaded Notepad++ but don't see the error on line 582?

Attached is my notepad file.  I will send the xml to you in an email since this says I can't attach xml file
[fll-2019_city-shaper-MN-jmb-v7.txt](https://github.com/jpschewe/fll-sw/files/3537289/fll-2019_city-shaper-MN-jmb-v7.txt)

**Comment by jpschewe** [comment]
Replied in email. Missing closing ">" on the opening element for the "range".
