### ISSUE TITLE
Required Judging Categories

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#757]
There was discussion at the Head Judge meeting regarding Categories that are required in order to be eligible for Awards.  In Research Project (now called Innovation Project) teams MUST have the following in order to be eligible for a Project Award:
Problem Identification
Team Solution
Sharing

If any of these is marked ND, we would like it highlighted or something on the reports.  Not sure what this entails and it is not a priority for this year

Underlying issue:  Teams have stopped Sharing because they want to do a patent and feel that sharing with others may encourage others to steal their idea.  So we had a team in Callbacks at State that did not share but had high enough scores on all the other goals that they still Won Project for their judging group and made it to CallBacks.   The Judge (Holly) pointed it out so they didn't win at State.  But in theory, they shouldn't have even been called back and the second place Project team should have been the one to callbacks.

**Comment by jpschewe** [comment]
The flag for if a goal is required or not already exists. It's used to put an asterisk next to the goal on the subjective sheets.

**Comment by jpschewe** [comment]
Once I finished #766 this wasn't too hard to support, so I've added it. The final scores and categorized scores reports will have "@" next to scores where one of the required goals is zero.
