### ISSUE TITLE
Asterisk on Innovation Project

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#766]
Can we add "*Required for Award Consideration" in RED on the Innovation Project  - See the attached rubric for example
[innovation project rubric.pdf](https://github.com/jpschewe/fll-sw/files/3607377/innovation.project.rubric.pdf)

I couldn't figure out how to make it appear on a line by itself when I updated the xml

**Comment by jpschewe** [comment]
I was able to go back in the source code history and pull the changes back in. Here is what I get. How does this look?
[subjective-project.pdf](https://github.com/jpschewe/fll-sw/files/3613288/subjective-project.pdf)

**Comment by jeanniebadger** [comment]
The red asterisks look good.
will you also be able to add the red "Required for Award Consideration" in the instructions on the Innovation Project rubric

**Comment by jpschewe** [comment]
@jeanniebadger  it's already there at the bottom.

**Comment by jpschewe** [comment]
I just moved it to the top to try and match the one that you posted earlier. How is this?
[subjective-project-3.pdf](https://github.com/jpschewe/fll-sw/files/3613340/subjective-project-3.pdf)

**Comment by jeanniebadger** [comment]
This looks great.  Thank you!
