### ISSUE TITLE
Changes to City Shaper Score Sheet

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#771]
Some Changes to the Score Sheet:
1.  More Space and a Line between header (Time:, Team #, Name, etc) and the "Fit in Small Inspection Area"
2.  Mission 12 - Change Wording to say "Color Matching Unit Completely In & Flatdown in Circle Red",  "Color Matching Unit Completely In & Flatdown in Circle Tan" &  "Color Matching Unit Completely In & Flatdown in Circle White"
3.  Mission 14 - Change Wording to say "Remaining Tokens on Field" 
4.  Mission 14 - Change Order of choice for # of Tokens to be "6/5/4/3/2/1/0"  (The Refs thought this would be easier to count)

**Comment by jpschewe** [comment]
The wording changes are done.

The sorting of scores for tokens can't be changed. The values for all goals are sorted from lowest score to highest score. Changing this one would change all of them.

I'm looking into the spacing.

**Comment by jpschewe** [comment]
@jeanniebadger  Here's an updated score sheet with space at the top and a line. How does this look?
[scoreSheet-2.pdf](https://github.com/jpschewe/fll-sw/files/3741792/scoreSheet-2.pdf)

**Comment by jeanniebadger** [comment]
This scoresheet looks good.  Thank you

I will let the Refs know that the tokens need to remain in that order.
