### ISSUE TITLE
Error when trying to upzip - fll-sw-14..0.1 zip file

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#772]
![image](https://user-images.githubusercontent.com/45802417/67048740-5b8d7c00-f0fa-11e9-9b72-000f5deb24e7.png)

**Comment by jpschewe** [comment]
@jeanniebadger please check the size of the downloaded file against the file size on the site. I suspect you only got a partial file.

**Comment by jpschewe** [comment]
I just downloaded the file and it opens fine here. I expect you got a partial file again.
