### ISSUE TITLE
Not Showing Run #4 on Scoreboard

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#785]
This is more of an FYI - 

Sharla went to Head to Head - Edited parameters
Initialized Brackets then was able to enter 4th round for score
But it did not show the Run #4 on the Scoreboard

This could have been part of the previously identified bug.

Won't be needed to change because for the rest of REGIONALS we will not score or display the 4th Run score anyway.

PRIORITY:  Zero - Again more of an FYI

**Comment by jpschewe** [comment]
This is expected, that's why I added the checkbox.
