### ISSUE TITLE
Awards report

### ISSUE THREAD

**Issue by jpschewe** [jpschewe/fll-sw#795]
@jeanniebadger would like a report like the attached file.
[Eagan Awards_11.16.19.pdf](https://github.com/jpschewe/fll-sw/files/3990720/Eagan.Awards_11.16.19.pdf)

We need to identify what information is available from where and how to get the judges to input it into the computer. This can be used as a start on the awards script, ticket #211.

**Comment by jpschewe** [comment]
Use Apache FOP for creating the PDF.

**Comment by jpschewe** [comment]
@jeanniebadger I'm looking at adding 2 properties to Tournament for this report. These properties are "type" and "next tournament type". They would both be "Regional", "Sectional", "State" or Other where the user can specify whatever (possibly empty) text that they want. The thinking here is that the Minneapolis Public Schools and St. Paul Public Schools tournaments would be specified as no text for the type and the next tournament type specified as "State". The other tournaments would follow the obvious mappings. Does this make sense from your perspective? Should the MSP and SPPS tournaments be called "Sectional" tournaments?

**Comment by jpschewe** [comment]
Any changes to the database for this ticket will be part of version 20.

**Comment by jeanniebadger** [comment]
Can we call minneapolis an st paul MPS and SPPS?  They are kind of a
regional but not really because advancement out of them is different than a
regular regional.  And they are not truly a sectional because they didn't
advance from a regional.  We keep them very separate in the office.

**Comment by jpschewe** [comment]
So the report for Minneapolis would have "MPS: Minneapolis Public Schools" at the top where the example has "Regional: Dakota Hills Middle School, Eagan". Is that correct?

**Comment by jeanniebadger** [comment]
That sounds right

**Comment by jpschewe** [comment]
@jeanniebadger when looking at the teams advancing section, am I correct that there needs to be a subsection for each award group plus "Wild Card"? That's what I see on https://drive.google.com/file/d/1EujYLArJuw0JTzyQ9KRkwDCWiMH53Ayt/view 
Do you want the "Wild Card" section or can the teams be listed as part of their award group?

**Comment by jeanniebadger** [comment]
I am not sure about the answer on that!

Sometimes vicki lists it separate and sometimes she puts them all together.

She is out of office until jan 2 and is purpose fully not answering emails.

I personally would like the wild cards separate.  Mainly because sometimes
we pull all the wildcards from one judging group and that looks awkward to
teams on the report.

So at first glance, i would say separate but subject to change!

**Comment by jpschewe** [comment]
Here is the first version of my report. Some of the spacing is different. However all of the data is there and should be readable. If the order of the awards is important, let me know and I'll open a separate ticket for that. I have some ideas on it, but don't want to go through the effort if it's not needed.
[awardsReport-34.pdf](https://github.com/jpschewe/fll-sw/files/4014613/awardsReport-34.pdf)
