### ISSUE TITLE
Awards Printout - order of award groups

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#813]
Can we set up the Awards report to be entered and printed in this order:

Lakes, Woods, Prairie, Rivers, Marshes

**Comment by jpschewe** [comment]
It will involve you as a user needing to specify the order.

**Comment by jeanniebadger** [comment]
that would be okay

**Comment by jpschewe** [comment]
Make sure to import the new table.

Use the data when generating the report.
