### ISSUE TITLE
Reporting for State Seeding

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#816]
Looking for ability to pull sectional/MPS/SPPS data for teams advancing to state - would want scores, ranking for each judging category.  I can get the data off the pdf but it would be nice to get the data so I can put it right into excel - 
see image for an idea of the spreadsheet that gets created

![image](https://user-images.githubusercontent.com/45802417/73882894-883fdd80-4828-11ea-811b-42dc6e17169b.png)

Tasks:
- [X] review all references to `current_tournament_teams`, consider removing this view
  - only `FinalComputedScores.writeScores` is going to be an issue
- [x] allow one to compute scores for all tournaments in the database
- [x] use `FinalComputedScores.gatherRankedPerformanceTeams` to get the performance ranking
- [x] use `FinalComputedScores.gatherRankedSubjectiveTeams` to get the subjective information (per award group)
- [x] refactor or rewrite `FinalComputedScores.writeScores` to get the overall ranking (per award group)
- [x] write out CSV file with the specified columns
- [x] replace `performance_seeding_max` with something that takes the tournament
- [x] find or create test database

**Comment by jpschewe** [comment]
@jeanniebadger What are all of the columns that you want?
I see some coach information in there that isn't available.
To be clear, these are the scores from the most recent tournament a team was in before advancing to state, correct?

**Comment by jeanniebadger** [comment]
Coach info is just there because of the spreadsheet I was using.  

I would be looking for:
team #,  Team Name, Judging Group, Tournament, Score from each Judged sessions, place from each judged session, Top Performance score, rank from Performance, overall ranking

**Comment by jeanniebadger** [comment]
Yes, Scores would be from most recent advancing - generally Sectional but SPPS and MPS come directly from their regional

**Comment by jpschewe** [comment]
@jeanniebadger  the report shows all teams advancing to another tournament. If you filter on "Next Level" being "State" you should find the information that you are looking for.
[performance_scores.zip](https://github.com/jpschewe/fll-sw/files/5187918/performance_scores.zip)
