### ISSUE TITLE
Ability to show teams scores by Judging group

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#820]
For State specifically - 

wanted to break the scrolling of scores into Judging group so teams did not have to wait so long to see their scores projected -

**Comment by jpschewe** [comment]
For the regional and sectional tournaments I added an option to display only certain award groups on a particular display. I can add an option to let one choose judging groups as well. Would that be sufficient?

**Comment by jeanniebadger** [comment]
Yes that would be great
