### ISSUE TITLE
REST API in front of (SQL) backend storage

### ISSUE THREAD

**Issue by eengstrom** [jpschewe/fll-sw#825]
If we start to define a REST API, regardless of how the back-end stores the data, then we can start to re-develop applications that sit atop, and perhaps break them into smaller pieces.  This also allows us to add new plug-ins/applications more easily, perhaps gaining more other users as well.

**Comment by jpschewe** [comment]
REST API has already been started. Tickets can be opened for specific plug-ins/applications as needed.
