### ISSUE TITLE
Do "subjective" awards correlate to a subset of "parent category" numeric scores?

### ISSUE THREAD

**Issue by eengstrom** [jpschewe/fll-sw#830]
Instead of relying upon judges to subjectively pick awards for the traditional subjective categories (e.g. Innovative Solution, Creative Presentation, Robot Strategy & Innovation), it seems that these three (State Tournament) could come out of a subset of their parent categories.

e.g. "Project" scoring and rubrics have three sub-sections that (roughly) correspond to
 - Project - Research
 - Project - Innovative Solution
 - Project - Creative Presentation

Similarly, I think that "Robot Innovative Design" ("Robot - Strategy & Innovation" at state) might be clearly a subset of the numbers from the design judge.

To validate this, it would be nice to go back to previous years data and see how the picks made by the judges correlate with the numeric scores.  This is especially intriguing from State tournaments.

For non-State tournaments, we'd have to **NOT** separate awards by score-subset, at least for Project (but perhaps yes for Innovative Design).  This also begs the question if we do this, how do the traditional awards change.  i.e. if we tease out "Design" from "Innoative Design", which scores go into which awards, and are there any individual scores that factor into both?

Would really like to get input from Jeanne & Norm on this too.

**Comment by jpschewe** [comment]
After some discussion with Norm and Jeannie, this is being closed as OBE given the changes that FIRST has made to the awards.
