### ISSUE TITLE
Add the ability to turn off schedule constraints

### ISSUE THREAD

**Issue by jpschewe** [jpschewe/fll-sw#840]
When running a virtual tournament the constraints on time between events doesn't make sense. We need a way to disable this on in the scheduler UI and on web upload.

@jeanniebadger I expect that we still need to make sure 2 events aren't happening at the same time. Is that correct?

**Comment by jeanniebadger** [comment]
Yes we need to make sure a team isn't double booked

**Comment by jpschewe** [comment]
I think that the way to handle this is to mark the constraints for minimum transfer time to be a level (orange) between soft (yellow) and hard (red). Then the user can look closer at the orange constraint violations and device to skip them just like the yellow constrain violations.

**Comment by jpschewe** [comment]
@jeanniebadger  while looking into this I see that there's already an option for the user to specify the change time values in both the scheduler UI and in the website. I did find a bug when using these on the website when uploading a schedule. This bug will be fixed shortly and then you can use these values to specify 0 minutes of change time.

**Comment by jpschewe** [comment]
@jeanniebadger  see https://jenkins.mtu.net/job/FLL-SW/job/master/lastSuccessfulBuild/artifact/build/distributions/ for a version with this fixed.
