### ISSUE TITLE
Bug Report - Adding Non-Numeric Nominee

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#882]
Jon - when entering a non-numic nominee for the Engineering Excellence award on the demo site, this bug report was created.

/home/jpschewe/demo/fll-sw-linux-15.3.0/web/WEB-INF/bug_2021-01-13_15-3914279671444141907361.zip'

**Comment by jpschewe** [comment]
[bug_2021-01-13_15-3914279671444141907361.zip](https://github.com/jpschewe/fll-sw/files/5811456/bug_2021-01-13_15-3914279671444141907361.zip)

**Comment by jpschewe** [comment]
I can't reproduce the problem with the saved database or on the demo site.

**Comment by jpschewe** [comment]
The key is to enter a team for engineering excellence, which doesn't have any judge information. Then there is an error.
