### ISSUE TITLE
Generating Rubric PDF's error

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#893]
I received this bug report when generating all the Team Results reports.  
I was able to generate each team report individually using "Results for a SIngle Team" option.

![image](https://user-images.githubusercontent.com/45802417/107275326-37545d80-6a17-11eb-9a8d-2a4517520598.png)

Bug report saved to '/home/jpschewe/tournament/fll-sw-linux-15.6.0/web/WEB-INF/bug_2021-02-08_14-0717050250629660396263.zip', please notify the computer person in charge to look for bug report files.

**Comment by jpschewe** [comment]
@jeanniebadger  I just tried reproducing this with the database from the bug report and found no issues. I also tried generating it on the tournament server. Perhaps someone was making changes between when you tried the full team version and the individual team versions. Please try again.

**Comment by jpschewe** [comment]
@jeanniebadger  I'm not sure what to tell you here. I took the database from the bug report and loaded it up in my system and then generated the results without any problems. I didn't use the production server because I didn't want to interrupt the performance rounds by changing the tournament.

**Comment by jpschewe** [comment]
@jeanniebadger  I suggest you try downloading the database and see if running it locally is a problem. You also might try another computer to see if somehow this is related to who is doing the download, although that should not matter with this error.

**Comment by jpschewe** [comment]
@jeanniebadger  tells me that they were able to generate the full results today, so I think this is "fixed". I did add some additional logging that we can use to debug this if it happens again.
