### ISSUE TITLE
subject app comments UX needs work

### ISSUE THREAD

**Issue by eengstrom** [jpschewe/fll-sw#900]
First, entering comments into the subjective app is great.  Thanks.

A few ideas for improvments:
 - have a text box for each "Row" that you can enter comments **without** having to click on "comment" button.
 - Even if we have to keep the button, then something to allow one to type immediately after clicking - as it is now, you have to move the mouse to click in the box just to be able to type.  Granted, this is on a full computer, not tablet, so I might be asking too much.
 - the location of the text box under the "exceeds" column implies you only enter comments for exceeds.

**Comment by jpschewe** [comment]
On point one, that take up a lot of real-estate that we don't have when using a tablet.

On point 2, If you hit a tab once you click the button you can start typing immediately. Then tab and return to close the dialog.

On point 3, this matches the rubric sheets from FIRST. The head judge should be explaining this at training.

**Comment by eengstrom** [comment]
boo!  Ask Jeannie her thoughts.

**Comment by jpschewe** [comment]
She helped me design the app this past summer.
