### ISSUE TITLE
Finalist Schedule for Each Team

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#901]
Can this report be generated with individual pages instead of one Document - similar to the Team Rubrics?  Thinking to State this year of craziness, we plan to email each coach with their schedule so having the documents separate would make it easier - for us - maybe not for you!

**Comment by jpschewe** [comment]
@jeanniebadger  the issue with separate documents two-fold:
1) When we are back in person we need to open a bunch of documents to print everything
2) When one downloads the data, a zip file needs to be downloaded instead of a single PDF

**Comment by jeanniebadger** [comment]
Yep, I totally understand.  I would want this change for this season only - I know that is not what you want to hear!

**Comment by jpschewe** [comment]
If it's just for this season, then I suggest you split the PDF after it is downloaded. In the Microsoft Store there is a free application called "PDF Merger & Splitter". Install this, load a PDF and then there is an output option to extract each page as a separate file.
