### ISSUE TITLE
Edit Award Winners

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#902]
Non- numeric Awards are cleared if this tab is re-opened.  The Subjective Award winners are still in with their descriptions.

This image is from the 2/20/21 tournament:
![image](https://user-images.githubusercontent.com/45802417/108889385-ef663680-75d1-11eb-860e-ced243fa20a1.png)

Attached is the Awards Report that shows I entered all awards.  NOTE:  I went into the PDF after the report was generated and removed Judging Groups for the non-numeric awards because they are optional and might not be given across all judging groups.  I will need to change the xml file next year to make sure those awards are selected not checked for "Per Award Group"
[awardsReport_2-20-21.pdf](https://github.com/jpschewe/fll-sw/files/6031086/awardsReport_2-20-21.pdf)

**Comment by jpschewe** [comment]
@jeanniebadger can you give me some more detail on the exact steps that you followed to cause this problem? Did you have multiple tabs or browser windows open? In what order did you visit pages and what pages to cause this problem?

Also what version of the software are you running?

**Comment by jpschewe** [comment]
I believe I've been able to reproduce this.

1. Load a database
2. Goto the Reporting Page
3. Visit Enter the winners of awards for use in the awards report
4. Enter a non-numeric winner
5. Click Store
6. Reload the page and note that the information is missing

**Comment by jpschewe** [comment]
@jeanniebadger  if you goto https://jenkins.mtu.net/job/FLL-SW/job/master/ and pick a build later than 360 you will be able to see this fixed.
