### ISSUE TITLE
Generate Finalist Reports

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#903]
When trying to generate schedules for Finalist Judging.
I received first error when trying to put finalist info to screen.  I can't remember how to attach a flldb file here so I will email it.
[bug_2021-02-23_14-048370113897222876256.zip](https://github.com/jpschewe/fll-sw/files/6031564/bug_2021-02-23_14-048370113897222876256.zip)

When I try to generate Finalist Schedule PDF reports in Judge Room I get the bug report ending with 9030
[bug_2021-02-23_14-104081588499339879030.zip](https://github.com/jpschewe/fll-sw/files/6031581/bug_2021-02-23_14-104081588499339879030.zip)

Finalist Schedule for Each Team receives bug report with ending with 4601 
[bug_2021-02-23_14-1115310611007315344601.zip](https://github.com/jpschewe/fll-sw/files/6031588/bug_2021-02-23_14-1115310611007315344601.zip)

**Comment by jpschewe** [comment]
@jeanniebadger  thank you for the bug reports. The database is in the bug report, so you don't need to send it separately.

**Comment by jpschewe** [comment]
Error generating finalist schedule PDF and schedule for each team is fixed with commit b831197. This fixes handling of tournaments without dates.

**Comment by jpschewe** [comment]
@jeanniebadger I'm looking at the database in the bug report and there are no team scores. Is this what you were entering finalist scores? Can you be specific about the actions that you were doing? What pages you visited and where exactly you received the error?

I see some errors in your bug report about importing data, but nothing about entering new data.

**Comment by jeanniebadger** [comment]
Jon- 

Weird - this didn't hit my email as it usually does - I was coming out here to see if I had actually hit submit and saw your comments.
I was testing the sytem to get an idea of how the scheduling works.  I worked on a file that would have had no scores in it at the time.  I had set up the last tournament 2/20 and put State in the Judging Group and reset up the tournament.

**Comment by jpschewe** [comment]
OK, then I believe this is fixed.
