### ISSUE TITLE
Add Weighted Placement calc on Final Computed Scores

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#907]
As another point of discussion for Head Judges - especially looking to Wild Card selection, can we add a column with weighted average of placment within each judging category?  (Project place + CV Place + 1/2 Programm + 1/2 Design + performance)/4

This does not work nicely for State because all teams performance scores are in one group, but for Regionals and Sectionals(If we ever go back!)

**Comment by jpschewe** [comment]
This is a weighted rank. Take each rank and use the same weights as the scores and come up with an overall weighted rank. This shows teams that are consistently in the top N teams in each category.

**Comment by jpschewe** [comment]
Add this as another column to the right of overall score. I should look into shrinking the other columns or the margins to get more space left to right.

**Comment by jpschewe** [comment]
Last night during the head officials training we noticed that the math looks wrong on this column. Double check the math, the best team should have the lowest value.

**Comment by jeanniebadger** [comment]
The numbers add up correctly.  It looks like they are not divided by 4 to get the weighted average

**Comment by jpschewe** [comment]
@jeanniebadger I believe I have this fixed. See https://jenkins.mtu.net/job/FLL-SW/job/issues%252F907%252Ffix-weighted-rank/ for a release with this fixed.
The new report is here [finalComputedScores-fixed.pdf](https://github.com/jpschewe/fll-sw/files/7108375/finalComputedScores-fixed.pdf)
