### ISSUE TITLE
Error showing times in Subjective App

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#914]
This is NOT high priority but I would like it for State if not too much work.  I had a few judges enter scores on the wrong team because teams were not in time order in the subjective app.  

I am trying to put in times for Judging to populate teams in time order in the subjective app.  I know I will need to fool the system with false Core Values times but currently the app is showing Na:Na for the times.  I think I will actually change the Core Values times to start at 6 am - this will let me get the teams in before the 8:30 judging start
[StateScheduleWithTimes.xlsx](https://github.com/jpschewe/fll-sw/files/6094021/StateScheduleWithTimes.xlsx)

I am using the above spreadsheet using Sheet 4 to populate the data.  When I look at the Full Schedule by Team it appears that the times are correctly entered.
[schedule.pdf](https://github.com/jpschewe/fll-sw/files/6094028/schedule.pdf)

 

![image](https://user-images.githubusercontent.com/45802417/110183476-8bfbb600-7dd4-11eb-9600-c177674e903e.png)

**Comment by jpschewe** [comment]
@jeanniebadger  thanks for catching this. It seems that a library update broke things here. You're doing the right thing with the schedule, the web software just isn't doing the right thing with the data.
