### ISSUE TITLE
OverWriting State Award Group

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#916]
When I enter a team schedule, the Award Group is overwritten/replace with Judging Group

Here are the steps I followed:
Uploaded new Description to erase everything - tried both xml 21 and xml 22
Admin - Step 1 - Upload datafile for teams - Use Awards Group to define State - Used attached spreadsheet
[State2021TeamSchedule.xlsx](https://github.com/jpschewe/fll-sw/files/6103869/State2021TeamSchedule.xlsx)

![image](https://user-images.githubusercontent.com/45802417/110375330-73c7a900-8017-11eb-90d6-d52079d6f4be.png)
Admin - Step 5 - Change tournament to State
![image](https://user-images.githubusercontent.com/45802417/110375528-b12c3680-8017-11eb-814b-1c263bfb3a8a.png)
Admin - Step 7 - Upload schedules and change parameters to 15 minutes to avoid red warnings about time - note that AWARDS Group is default. (not sure if that means anything) I change those to the correct Judging categories
![image](https://user-images.githubusercontent.com/45802417/110376030-521af180-8018-11eb-9ce4-bf184a6b52c3.png)
![image](https://user-images.githubusercontent.com/45802417/110376115-6d85fc80-8018-11eb-99b2-61eae109d3b3.png)

It asks if I want to update team info, I say Skip All Changes

Then I look at Full Schedule Sorted by Team and it shows team Judging Group and Award Group is the same, no longer State
![image](https://user-images.githubusercontent.com/45802417/110376450-cfdefd00-8018-11eb-875f-11ef328eafc3.png)

If I try to do the Finalist Judging Schedule without adding the Schedule I get this error and bug report and message
![image](https://user-images.githubusercontent.com/45802417/110378101-cf476600-801a-11eb-8a4d-33320e8bf225.png)
[fll-sw_2021-03-08_14-20-24.1.log](https://github.com/jpschewe/fll-sw/files/6103966/fll-sw_2021-03-08_14-20-24.1.log)

**Comment by jpschewe** [comment]
@jeanniebadger  if you change the name of the column "AWARDS Group" to "Award Group", note that it's singular and the case matters, then it works.

**Comment by jpschewe** [comment]
@jeanniebadger  I've noted this issue on issue #34 and marked it as something to fix for next season.
