### ISSUE TITLE
Mark No Show on Rubric

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#920]
Can a Rubric be marked with "No Show" so in looking at the PDF's we don't wonder why a rubric is blank?

**Comment by jpschewe** [comment]
Sure, how do you want the "No Show" to appear on the page?

**Comment by jpschewe** [comment]
@jeanniebadger  how does this look?

[Innovation Project no show.pdf](https://github.com/jpschewe/fll-sw/files/6368765/Innovation.Project.no.show.pdf)

**Comment by jeanniebadger** [comment]
This looks perfect!  Thank you!

**Comment by jeanniebadger** [comment]
Can they un-"no show" and this will not show on the rubric?

**Comment by jpschewe** [comment]
Yes, whatever is currently stored in the database is what shows up when the rubric is printed.

**Comment by jeanniebadger** [comment]
Sounds good
