### ISSUE TITLE
Synchronize button - additional wording

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#922]
Could we add something near the Synchronize button telling judges not to press Synchronize unless they are connected to server?  I am thinking about how we will do next season and if they click on Synchronize while not connected the circle spins and spins but they don't know if it updated or not.

Don't make any changes yet - just thinking out loud?!?!  I know this is a training issue, but....how can we make it more clear without having to give out printed instructions (which no one reads anyway!)

**Comment by jpschewe** [comment]
We might be able to have something check if the server is available and give a better error message.

**Comment by jpschewe** [comment]
It looks like I already have the function to check if the server is online in index.js. That function needs to be modified to allow other actions to take place depending on the result, but that could provide the user with a useful error message if the server is offline and allow the synchronization to take place if the server is online.

**Comment by jeanniebadger** [comment]
Ok let's keep that in mind as we move forward with planning for the season.  I think that would be be a good improvement to make things easier for the judges and possibly refs!
