### ISSUE TITLE
Tablets used for live scoring

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#927]
I have been testing the scoresheet on an ipad and tablet.  There are a few graphical issues that make it challenging to use tablet instead of paper at tournament.

Can the submit buttons be made larger?

Can we add a place for teams and refs to input initials that they agree to the score?

Can we make the SCORE appear larger?  Bold or in a different color to make it stand out more?

This is not an exhaustive list of the changes but just some first time through suggestions

Tasks:
  - [x] yes/no buttons side by side full width
  - [x] use full width enumeration buttons
  - [x] Use range slider for counts less than 20
  - [x] increase the font size
  - [x] use the same font for performance score entry as subjective score entry
  - [x] tick marks on sliders

**Comment by jpschewe** [comment]
These are all possibilities. It is a matter of time to get it all done. Most of this is non-trival to do.

**Comment by jpschewe** [comment]
A college student forked the code years ago and added some of these items. His fork is at https://github.com/nickmcski/fll-sw. At the time I asked him for reasonable-sized pull requests, but he never responded. There are details about the large changes at #572. Perhaps this should be looked into again.

**Comment by jpschewe** [comment]
I found a version of the software running at http://13.59.244.18/fll-sw/ that looks like it may look better on a tablet for performance score entry. However this isn't the same as the fork, so I'm not sure where the source is and how to get those changes. I can probably figure out a fair amount of the UI changes by looking at the pages themselves without the backend code.

**Comment by jpschewe** [comment]
Doing some more poking around on this site, the database version is 15. The fork has the same database version. The software version on the fork is 11.1-45-g6aeaf6e1. The fork uses tomcat 8.0.9, the other website uses tomcat 8.5.11. So these are clearly different versions.

Looking through the forks on GitHub I don't see this version showing up. So I'm not sure what source code changes are behind it.
