### ISSUE TITLE
Initials on performance score page

### ISSUE THREAD

**Issue by jpschewe** [jpschewe/fll-sw#929]
A question from @jeaniebadger from #927 
Can we add a place for teams and refs to input initials that they agree to the score?

**Comment by jpschewe** [comment]
The initials fields should only be shown when score entry is done electronically. Additionally when in this mode there is no need for the second check so that score should be immediately verified.

**Comment by jeanniebadger** [comment]
Jon - 
In testing this a little bit on tablets, it would make sense to have the initial feature at the bottom of the scoresheet by the submit score button

**Comment by jpschewe** [comment]
Thinking about this more. When a ref has selected a table per #935 then instead of showing the verify link at the bottom of the form show text asking if the team agrees with the score and a yes/no button. Behind the scenes this is the same as the verification button. However when using this functionality make sure that the warning about verification on initial entry isn't shown.
