### ISSUE TITLE
While editing awards some entries disappear

### ISSUE THREAD

**Issue by jpschewe** [jpschewe/fll-sw#995]
This happened twice today on different laptops. Someone entered a score and clicked submit and then when we looked later the entry wasn't there. While this was happening the existing entries were being edited to change the place.

**Comment by jpschewe** [comment]
Add a positive confirmation when scores are saved. 

Check all possible exits from the save method.

**Comment by jpschewe** [comment]
Added debugging and user feedback for the next set of tournaments. Hopefully this will show us what is going on.

**Comment by jeanniebadger** [comment]
Mary Trandem claims that she lost scores and comments at State.  She also thought her comments moved from one team to another.  I have not been able to replicate

**Comment by jpschewe** [comment]
@jeanniebadger  this is about the award winners, not the subjective judging application.

**Comment by jpschewe** [comment]
We didn't see this happen again, cannot reproduce.
